### ISSUE TITLE
Query GB holidays for a previous year always returns Christmas 2015

### ISSUE THREAD

**Issue by dipockdas** [joshtronic/holidayapi.com#22]
If you issue the following query:
http://holidayapi.com/v1/holidays?country=GB&year=2000
The result is correct except for the Christmas and Boxing Day entries - which are always reported for the current (2015) year. 

Result:
{"status":200,"holidays":{"2000-01-01":[{"name":"New Year's Day","country":"GB","date":"2000-01-01"}],"2000-04-21":[{"name":"Good Friday","country":"GB","date":"2000-04-21"}],"2000-04-24":[{"name":"Easter Monday","country":"GB","date":"2000-04-24"}],"2000-05-01":[{"name":"Early May Bank Holiday","country":"GB","date":"2000-05-01"}],"2000-05-29":[{"name":"Spring Bank Holiday","country":"GB","date":"2000-05-29"}],"2000-08-28":[{"name":"Summer Bank Holiday","country":"GB","date":"2000-08-28"}],"2015-12-25":[{"name":"Christmas (possibly in lieu)","country":"GB","date":"2015-12-25"}],"2015-12-28":[{"name":"Boxing Day (possibly in lieu)","country":"GB","date":"2015-12-28"}]}}

Results are consistent -  Tested the following years: 2014, 2010, 2005.

**Comment by joshtronic** [comment]
Good eye! I was thinking "weekday" was what was throwing it off, but that appears to be sound. I suspect it has something to do with how the year is injected into the rule:

January 1st turns into January 1st :year
while 24 December +1 weekday turns into 24 December +1 weekday :year

Upon looking at the US file, in those scenarios I am placing the year variable into the string.... will close this once the fix is in there. Also happening on the NO holidays.

Thanks for reporting this!

**Comment by joshtronic** [comment]
Whoops, didn't fix it... reopening.

**Comment by joshtronic** [comment]
Actually, seems like we're good. Must have been stuck in the cache. Gonna close this, feel free to verify and reopen if anything is amiss. Thanks again!

**Comment by dipockdas** [comment]
Thanks - verified and working.
